django-estore-master/estore/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$',views.cart_detail,name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),

]

django-estore-master/estore/estore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),
    path('cart/',include('cart.urls')),
]

django-estore-master/estore/storeapp/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from storeapp import views
from django.contrib.auth import views as auth_views

app_name = 'storeapp'

urlpatterns = [
    url(r'^$',views.Indexview.as_view(),name='index'),
    url(r'^login/$',views.loginview,name='login'),
    url(r'^logout/$',auth_views.logout,{'next_page':'storeapp:index'},name='logout'),
    url(r'^item/(?P<slug>[-\w]+)/$',views.item_detail,name='item_detail'),
    url(r'^items/(?P<cat_slug>[-\w]+)/$',views.cat_query,name='cat_query'),
    url(r'^brand/(?P<brand_slug>[-\w]+)/$',views.brand_query,name='brand_query'),
    url(r'^signup/$',views.signupview,name='signup'),
    url(r'^confirm-order/$',views.con_order,name='con_order'),
    url(r'^order-succes/$',views.fin_order,name="fin_order"),
    url(r'^item-search/$',views.searchview,name='item-search')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-estore-master/estore/orders/models.py
from django.db import models

# Create your models here.

django-estore-master/estore/storeapp/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.



class Categories(models.Model):
    cat_name = models.CharField(max_length=200)
    slug = models.SlugField(allow_unicode=True,default='cat-slug')
    def __str__(self):
        return self.cat_name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.cat_name)
        super().save(*args,**kwargs)

class Brand(models.Model):
    brand_name = models.CharField(max_length=200)
    category = models.ForeignKey(Categories,related_name='brand',on_delete='CASCADE')
    slug = models.SlugField(allow_unicode=True,default='brand-slug')

    def __str__(self):
        return self.brand_name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.brand_name)
        super().save(*args,**kwargs)

class Item(models.Model):
    brand = models.ForeignKey(Brand,related_name='item',on_delete='CASCADE')
    item_name = models.CharField(max_length=200)
    slug = models.SlugField(allow_unicode=True,default='item-name')
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='pictures',null=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.item_name)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.item_name


class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete='CASCADE',related_name='userinfo')
    city = models.CharField(max_length=200)
    house = models.CharField(max_length=200)
    def __str__(self):
        return self.user.username

class Order(models.Model):
    user = models.ForeignKey(UserInfo,on_delete='CASCADE',related_name='order')
    product = models.ForeignKey(Item,on_delete='CASCADE',related_name='product')
    price = models.DecimalField(max_digits=10,decimal_places=2)
    quantity = models.PositiveIntegerField()
    def __str__(self):
        return  'Order {}'.format(self.id)

django-estore-master/estore/storeapp/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import UserInfo

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username','email')
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'})
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Password didn't match!")
        return cd['password2']

class UserInfoForm(forms.ModelForm):
    city = forms.CharField(label='City',widget=forms.TextInput(attrs={'class':'form-control'}))
    house = forms.CharField(label='House No.',widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = UserInfo
        fields = ('city','house')
        widgets = {
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'house':forms.TextInput(attrs={'class':'form-control'}),

        }

django-estore-master/estore/orders/views.py
from django.shortcuts import render

# Create your views here.

django-estore-master/estore/storeapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login
from django.urls import reverse
from django.contrib.auth.models import User
from storeapp import models
from django.shortcuts import render, get_object_or_404
from storeapp.forms import UserRegisterForm,UserInfoForm
from cart.cart import Cart
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

User = get_user_model()
# Create your views here.


class Indexview(TemplateView):
    template_name = 'storeapp/index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        categories = models.Categories.objects.all()
        items = models.Item.objects.filter(available=True)[:9]
        context['items'] = items
        context['categories'] = categories
        return context

def item_detail(request,slug):
    item = models.Item.objects.filter(slug=slug)
    return render(request,'storeapp/item_detail.html',{'item':item})


def cat_query(request,cat_slug):
    category = models.Categories.objects.all()
    cat = get_object_or_404(models.Categories,slug=cat_slug)
    brand = models.Brand.objects.filter(category=cat)
    catn = cat.cat_name
    items = models.Item.objects.filter(brand__category__cat_name=catn)
    return render(request,'storeapp/item_query.html',{'items':items,'brand':brand,'category':category})

def brand_query(request,brand_slug):
    category = models.Categories.objects.all()
    brands = get_object_or_404(models.Brand,slug=brand_slug)
    catn = brands.category
    items = models.Item.objects.filter(brand=brands)
    brand = models.Brand.objects.filter(category__cat_name=catn)
    return render(request,'storeapp/item_query.html',{'items':items,'brand':brand,'category':category})


@login_required
def con_order(request):
    cart = Cart(request)
    return render(request,"storeapp/order.html",{"cart":cart})

@login_required
def fin_order(request):
    user1 = request.user
    use = models.UserInfo.objects.get(user=user1)
    cart = Cart(request)
    for item in cart:
        models.Order.objects.create(user=use,product=item['product'],
                                    price=item['price'],quantity=item['quantity'])
    cart.clear()
    return render(request,"storeapp/order_success.html",{'use':use})


def searchview(request):
    if request.method == 'GET':
        obj = request.GET.get('search')
        if obj:
            try:
                search_item = models.Item.objects.filter(item_name__icontains=obj)
            except ExplicitException:
                pass
            # search_item = models.Item.objects.filter(brand__category__cat_name__icontains=obj)
            return render(request,"storeapp/item_search.html",{'search_item':search_item,'obj':obj})
    else:
        return render(request,"storeapp/item_search.html",{'obj':obj})


def loginview(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('storeapp:index'))
            else:
                return HttpResponse('User is not active')
        else:
            return HttpResponse('wrong username and password')
    else:
        return render(request,'storeapp/base.html',{})

def signupview(request):
    if request.method == "POST":
        user_form = UserRegisterForm(request.POST)
        info_form = UserInfoForm(request.POST)

        if user_form.is_valid() and info_form.is_valid():
            new = user_form.save(commit=False)
            new.set_password(user_form.cleaned_data['password'])  #does encryption
            new.save()
            info = info_form.save(commit=False)
            info.user = new
            info.save()
            return render(request,'storeapp/signup.html',{'user_form':user_form,'info_form':info_form})
        else:
            return HttpResponse('ValidationError')
    else:
        user_form = UserRegisterForm()
        info_form = UserInfoForm()
        return render(request,'storeapp/signup.html',{'user_form':user_form,'info_form':info_form})

django-estore-master/estore/storeapp/templates/storeapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EStore</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script  src="{% static 'javascript/index.js' %}"   type="text/javascript"> -->
    </script>
  </head>
  <body>

    <!-- navbar  -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #2874f0;">
       <a class="navbar-brand" href="{% url 'storeapp:index' %}" style="color:white">EStore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>

       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
             <a class="nav-link" href="{% url 'storeapp:index' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i>Home <span class="sr-only">(current)</span></a>
           </li>
         </ul>
         {% block body_block %}
         {% endblock %}
         <ul class="navbar-nav">
           <li>
             <div id="cart-container">
             <div id="cart">
               {% with total_items=cart|length %}
               <strong><a class="nav-link" style="color:white" href="{% url 'cart:cart_detail' %}">
                 <i class="fa fa-shopping-cart" aria-hidden="true"></i>Cart<span class="badge badge-pill badge-danger">{{ total_items }}</span>
               </a>
              </strong>
              {% endwith %}
             </div>
              <span id="itemCount"></span>
            </div>
           </li>
         </ul>
      {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link" style="color:white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user" aria-hidden="true"></i> {{ request.user.username }}
      </a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <a class="dropdown-item"  href="{% url 'storeapp:logout' %}">logout</a>

          </div>
        </li>
      </ul>

      {% else %}


         <ul class="navbar-nav">
           <li class="nav-item dropdown">
             <a class="nav-link"  style="color:white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fa fa-user" aria-hidden="true"></i>
      Login
             </a>
             <div class="dropdown-menu dropdown-menu-right">
               <form class="px-4 py-3" action="{% url 'storeapp:login' %}" method="post" >
                {% csrf_token %}
                 <div class="form-group">
                   <label for="exampleDropdownFormEmail1">Username</label>
                   <input type="text" name='username' class="form-control" id="exampleDropdownFormEmail1" placeholder="username">
                 </div>
                 <div class="form-group">
                   <label for="exampleDropdownFormPassword1">Password</label>
                   <input type="password" name="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
                 </div>
                 <input type="submit"  value="Login">
                </form>

               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="{% url 'storeapp:signup' %}">New around here? Sign up</a>
               <a class="dropdown-item" href="#">Forgot password?</a>
             </div>
           </li>
         </ul>
      {% endif %}
       </div>
    </nav>
    <!-- navbarend -->


    {% block body_content %}
    {% endblock %}
    <!-- footer -->
    <div  style="padding-top:40px;">
      <footer class="py-5 bg-dark" >
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; EStore 2018</p>
        </div>
        <!-- /.container -->
      </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

django-estore-master/estore/storeapp/templates/storeapp/index.html
<!DOCTYPE html>
{% extends "storeapp/base.html" %}
{% load static %}
 {% block body_block %}
 <ul class="navbar-nav mr-auto">
   <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'storeapp:item-search' %}">
     <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
     <button class="btn btn-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
   </form>
 </ul>
 {% endblock %}

 {% block body_content %}

 <!-- slider -->

<div class="container-fluid" style="padding-top:20px">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="{% static 'images/1.jpg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="{% static 'images/2.jpg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="{% static 'images/3.jpg' %}" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <!-- sliderend -->

    <div class="container" >
        <div class="row">
       	<div class="col-sm-3"style="padding-top:50px;">
       		<div class="list-group">
              <button type="button" class="list-group-item list-group-item-action active">
                Categories
              </button>
              {% for c in categories %}
              <a href="{% url 'storeapp:cat_query' cat_slug=c.slug %}" class="list-group-item list-group-item-action">{{c}}</a>
              {% endfor %}
          </div>

       	</div>
       	<div class="col-sm-9">

      <div class="container-fluid" style="padding-top:20px">

        <!-- <h1>{{item_list}}</h1> -->
        <div class="row">

          {% for item in items %}
          <div class="col-sm-4" style="padding-top:20px">
            <div class="card h-100">
                <a href="{% url 'storeapp:item_detail' slug=item.slug %}"><img class="card-img-top" src="{{item.image.url}}" ></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{% url 'storeapp:item_detail' slug=item.slug %}">{{item.item_name}}</a>
                    </h4>
                    <h5>Rs.{{item.price}}</h5>
                    <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                 </div>
                 <div class="card-footer">
                   <a href="{% url 'cart:cart_add' product_id=item.pk %}" ><button type="button" class="btn btn-danger">Add To Cart</button>
                   </a>
                  </div>
            </div>
          </div>
          {% endfor %}



        </div>

      </div>


        </div>
      </div>
    </div>

 {% endblock %}

django-estore-master/estore/storeapp/templates/storeapp/item_detail.html
<!DOCTYPE html>

{% extends "storeapp/base.html" %}
{% load static %}
{% block body_block %}
<ul class="navbar-nav mr-auto">
  <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'storeapp:item-search' %}">
    <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
  </form>
</ul>
{% endblock %}
 {% block body_content %}
 <div class="container">

    <div class="row">
  {% for cat in item %}
      <div class="col-lg-5">
        <img class="card-img-top img-fluid" src="{{cat.image.url}}" style="padding-top:70px">


      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-7">

        <div class="card mt-4">

          <div class="card-body">
            <h3 class="card-title">{{cat.item_name}}</h3>
            <h4>Rs.{{cat.price}}</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis molestias iure, ducimus!</p>
          </div>
        </div>
        {% endfor  %}
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
          <div class="card-header">
            Product Reviews
          </div>
          <div class="card-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <a href="#" class="btn btn-success">Leave a Review</a>
          </div>
        </div>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->

    </div>

  </div>


  {% endblock %}

django-estore-master/estore/storeapp/templates/storeapp/item_query.html
<!DOCTYPE html>

{% extends "storeapp/base.html" %}
{% load static %}
{% block body_block %}
<ul class="navbar-nav mr-auto">
  <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'storeapp:item-search' %}">
    <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
  </form>
</ul>
{% endblock %}
 {% block body_content %}
<div class="container" style="padding-top:50px;">
  <div class="row">
    <div class="col-sm-3">
      <div class="list-group">
          <button type="button" class="list-group-item list-group-item-action active">
            Categories
          </button>
          {% for c in category %}
          <a href="{% url 'storeapp:cat_query' cat_slug=c.slug %}" class="list-group-item list-group-item-action">{{c}}</a>
          {% endfor %}
      </div>
      <div class="list-group" style="padding-top:20px">
          <button type="button" class="list-group-item list-group-item-action active">
            Brands
          </button>
          {% for b in brand %}
          <a href="{% url 'storeapp:brand_query' brand_slug=b.slug %}" class="list-group-item list-group-item-action">{{b.brand_name}}</a>
          {% endfor %}
        </div>
    </div>
    <div class="col-sm-9">
      <div class="container-fluid" style="padding-top:20px">
        <!-- <h1>{{item_list}}</h1> -->
        <div class="row">
          {% for i in items %}
          <div class="col-sm-4" style="padding-top:20px">
            <div class="card h-100">
                <a href="{% url 'storeapp:item_detail' slug=i.slug %}"><img class="card-img-top" src="{{i.image.url}}" width="200px"></a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="{% url 'storeapp:item_detail' slug=i.slug %}">{{ i.item_name }}</a>
                    </h4>
                    <h5>Rs.{{i.price}}</h5>
                    <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                   </div>
                   <div class="card-footer">
                    <a href="{% url 'cart:cart_add' product_id=i.pk %}" ><button type="button" class="btn btn-danger">Add To Cart</button>
                    </a>
                  </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

django-estore-master/estore/storeapp/templates/storeapp/item_search.html
{% extends 'storeapp/base.html' %}

{% block body_block %}
<ul class="navbar-nav mr-auto">
  <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'storeapp:item-search' %}">
    <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
  </form>
</ul>
{% endblock %}

{% block body_content %}
{% if search_item %}
<div class="container">
  <div class="row">
    <p>Results for the keyword "{{obj}}"</p>
    <div class="col-sm-3">

    </div>
    <div class="col-sm-9">
      <div class="container-fluid" style="padding-top:20px">
        <!-- <h1>{{item_list}}</h1> -->
        <div class="row">

          {% for i in search_item %}
          <div class="col-sm-4" style="padding-top:20px">
            <div class="card h-100">
                <a href="{% url 'storeapp:item_detail' slug=i.slug %}"><img class="card-img-top" src="{{i.image.url}}" width="200px"></a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="{% url 'storeapp:item_detail' slug=i.slug %}">{{ i.item_name }}</a>
                    </h4>
                    <h5>Rs.{{i.price}}</h5>
                    <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                   </div>
                   <div class="card-footer">
                    <a href="{% url 'cart:cart_add' product_id=i.pk %}" ><button type="button" class="btn btn-danger">Add To Cart</button>
                    </a>
                  </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% else %}
    <p>No results found for the Keyword "{{obj}}"</p>
  </div>
</div>


{% endif %}

{% endblock %}

django-estore-master/estore/storeapp/templates/storeapp/order.html
{% extends "storeapp/base.html" %}
{% block body_content %}
<div class="jumbotron">
  <div class="container">
        <table>
          <tr>
            <th><h1>Your orders:</h1></th>
            <th></th>
          </tr>
          {% for i in cart %}
          {% with p=i.product %}
          <tr>
          <td><b>{{i.quantity}}x</b>  {{p.item_name}}</td>
          <td><b>Rs. {{i.price}}</b></td>
          </tr>
          {% endwith %}
          {% endfor %}
          <tr>
            <td></td>
            <td><h3>Total Amount: Rs. {{cart.get_total_price}}</h3>
            <a href="{% url 'storeapp:fin_order' %}" ><button type="button" class="btn btn-danger">Confirm Order!</button>
            </a></td>
          </tr>

        </table>
  </div>
</div>
{% endblock %}

django-estore-master/estore/storeapp/templates/storeapp/order_success.html
{% extends "storeapp/base.html" %}
{% load staticfiles %}
{% block body_content %}
<div class="jumbotron">
  <center>
    <img src="{% static 'images/tick.png' %}" width="100px">
    <h1>Your order has been placed successfully!</h1>
    <br><br><br><br><br><br><br><br><br>
    <h1></h1>
  </center>

</div>

{% endblock %}

django-estore-master/estore/storeapp/templates/storeapp/signup.html
<!DOCTYPE html>
{% extends "storeapp/base.html" %}

{% block body_content %}
<div class="container">
  <div class="row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-6" style="margin-top:100px">
      <div class="jumbotron">
      <h3><b>Create an account</b></h3>
           <form method="post">
             {% csrf_token %}
             {{ user_form.as_p }}
             {{ info_form.as_p }}
          <input type="submit" class="btn btn-primary" value="Signup"></input>
        </form>
    </div>
    <div class="col-sm-3">
    </div>
  </div>
</div>
</div>
{% endblock %}