django-estore-master/estore/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$',views.cart_detail,name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),

]

django-estore-master/estore/estore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),
    path('cart/',include('cart.urls')),
]

django-estore-master/estore/storeapp/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from storeapp import views
from django.contrib.auth import views as auth_views

app_name = 'storeapp'

urlpatterns = [
    url(r'^$',views.Indexview.as_view(),name='index'),
    url(r'^login/$',views.loginview,name='login'),
    url(r'^logout/$',auth_views.logout,{'next_page':'storeapp:index'},name='logout'),
    url(r'^item/(?P<slug>[-\w]+)/$',views.item_detail,name='item_detail'),
    url(r'^items/(?P<cat_slug>[-\w]+)/$',views.cat_query,name='cat_query'),
    url(r'^brand/(?P<brand_slug>[-\w]+)/$',views.brand_query,name='brand_query'),
    url(r'^signup/$',views.signupview,name='signup'),
    url(r'^confirm-order/$',views.con_order,name='con_order'),
    url(r'^order-succes/$',views.fin_order,name="fin_order"),
    url(r'^item-search/$',views.searchview,name='item-search')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-estore-master/estore/cart/models.py
from django.db import models

# Create your models here.

django-estore-master/estore/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
        quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                          coerce=int)
        update = forms.BooleanField(required=False,
                                    initial=False,
                                    widget=forms.HiddenInput)

django-estore-master/estore/cart/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from storeapp.models import Item
from .cart import Cart
from cart.forms import CartAddProductForm


# Create your views here.


def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Item,id=product_id)
    cart.add(item=product)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
         cd = form.cleaned_data
         cart.add(item=product,
         quantity=cd['quantity'],
         update_quantity=cd['update'])
    return HttpResponseRedirect(reverse('storeapp:index'))

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm( initial={'quantity': item['quantity'],
                                                           'update': True})
    return render(request,'cart/cart_detail.html',{'cart':cart})

def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Item,id=product_id)
    cart.remove(product_id)
    return HttpResponseRedirect(reverse('cart:cart_detail'))

django-estore-master/estore/cart/templates/cart/cart_detail.html
<!DOCTYPE html>
{% extends 'storeapp/base.html' %}
{% load static %}
{% block body_content %}

<div class="container">
  <table class="table table-hover">
     <thead class="thead-dark">
       <tr>
         <th>Sr.No.</th>
         <th>Item</th>
         <th>Image</th>
         <th>Price</th>
         <th>Quantity</th>
         <th></th>
       </tr>
     </thead>
     <tbody>
       {% for i in cart %}
       {% with product=i.product %}
       <tr>
         <td>{{forloop.counter|add:0}}</td>
         <td>{{product.item_name}}</td>
         <td><img class="card-img-top" src="{{product.image.url}}" style="width:100px"></td>
         <td>Rs. {{i.price}}</td>
         <td>
          <form action="{% url "cart:cart_add" product.pk %}" method="post">
          {{ i.update_quantity_form.quantity }}
          {{ i.update_quantity_form.update }}
          <input type="submit" value="Update">
          {% csrf_token %}
          </form>
         </td>
         <td><a href="{% url 'cart:cart_remove' product_id=product.pk %}"><button type="button" class="btn btn-danger">Remove</button></a></td>
       </tr>
       {% endwith %}
       {% endfor %}
       <thead class="thead-dark">
         <tr>
           <th></th>
           <th></th>
           <th></th>
           <th>Total: Rs. {{ cart.get_total_price }}</th>
           <th><a href="{% url "storeapp:con_order" %}" ><button type="button" class="btn btn-success">Place Order</button>
           </a></th>
           <th></th>
         </tr>
       </thead>
     </tbody>
   </table>
</div>

{% endblock %}